name: Docker Image CI

on:
  push:
    branches:
      - main # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true

      - name: 检查 Docker Buildx 平台
        run: |
          echo "Available platforms:"
          echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Verify Docker login
        run: |
          echo "Docker login status:"
          docker info

      - name: Build and push multi-platform Docker image
        run: |
          echo "Building Docker image for platforms: linux/amd64, linux/arm64"
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/nestjs-mn:1.0.0 --push .

      - name: Check Docker images
        run: |
          echo "Docker images:"
          docker images